---
version: '3.3'
services:
  db:
    env_file:
      - .env
    build:
      context: ./db
    image: 'postgres:tomcat'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - '/opt/pgdata:/var/lib/postgresql/data'
      - './db/pginit:/docker-entrypoint-initdb.d'
    user: '1000:1000'
