---
version: '3.3'
services:
  prod:
    env_file:
      - ./mvn/.env
    build:
      context: ./mvn
    image: 'maven:hw13'
    networks:
      - dbnet
    volumes:
      - 'project:/usr/src/target'
    depends_on:
      - web

  db:
    env_file:
      - ./db/.env
    build:
      context: ./db
    image: 'postgres:hw13'
    restart: always
    networks:
      dbnet:
        aliases:
          - dbsrv.loc
    ports:
      - '5432:5432'
    volumes:
      - './localdata/pgdata:/var/lib/postgresql/data'
      - './db/pginit:/docker-entrypoint-initdb.d'
    user: '1000:1000'

  web:
    env_file:
      - ./web/.env
    build:
      context: ./web
    image: 'tomcat:hw13'
    restart: always
    networks:
      - dbnet
    ports:
      - '8080:8080'
    volumes:
      - 'project:/usr/local/tomcat/webapps'
    depends_on:
      - db

volumes:
  project:

networks:
  dbnet: