---
version: '3.3'
services:
  db:
    build:
      context: ./db
    image: 'postgres:tomcat'
    restart: always
    volumes:
      - '/opt/pgdata:/var/lib/postgresql/data'
      - './db/pginit:/docker-entrypoint-initdb.d'
    user: '1000:1000'
