---
version: '3.3'
services:
  db:
    image: 'postgres:11.15-bullseye'
    restart: always
    environment:
        POSTGRES_PASSWORD: Passw0rd
    volumes:
      - '/opt/pgdata:/var/lib/postgresql/data'
    user: '1000:1000'
