---
version: '3.3'
services:
  db:
    env_file:
      - .env
    build:
      context: ./db
    image: 'postgres:hw13'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './localdata/pgdata:/var/lib/postgresql/data'
      - './db/pginit:/docker-entrypoint-initdb.d'
    user: '1000:1000'
  web:
    build:
      context: ./web
    image: 'tomcat:hw13'
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - '/localdata/tcdata:/usr/local/tomcat/webapps'
    #  - './db/pginit:/docker-entrypoint-initdb.d'
    #user: '1000:1000'
