---
version: '3.3'
services:
#  prod:
#    depends_on:
#      - db
#    env_file:
#      - ./mvn/.env
#    build:
#      context: ./mvn
#    image: 'maven:hw13'
#    networks:
#      - dbnet
#    volumes:
#      - 'webapps:/usr/src/target'

  db:
    env_file:
      - ./db/.env
    build:
      context: ./db
    image: 'mysql:hw13'
    restart: always
    networks:
      dbnet:
        aliases:
          - dbsrv.loc
    ports:
      - '3306:3306'
    volumes:
      - './localdata/pgdata:/var/lib/mysql'
      - './db/sqlinit:/docker-entrypoint-initdb.d'

#  web:
#    depends_on:
#      - db
#      - prod
#    env_file:
#      - ./web/.env
#    build:
#      context: ./web
#    image: 'tomcat:hw13'
#    restart: always
#    networks:
#      - dbnet
#    ports:
#      - '8080:8080'
#    volumes:
#      - 'webapps:/usr/local/tomcat/webapps'


#volumes:
#  webapps:

networks:
  dbnet: