CREATE DATABASE dbtom CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'tomcat'@'%' IDENTIFIED BY 'tomcat';
GRANT ALL PRIVILEGES ON dbtom . * TO 'tomcat'@'%';
SET SQL_SAFE_UPDATES = 0;
FLUSH PRIVILEGES;