CREATE DATABASE dbtom CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON dbtom.* TO 'tomcat'@'localhost' IDENTIFIED BY 'tomcat' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON dbtom.* TO 'tomcat'@'%' IDENTIFIED BY 'tomcat' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SET SQL_SAFE_UPDATES = 0;
